// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// parseString
CharacterVector parseString(CharacterVector x, int interval);
RcppExport SEXP GFUAPI_parseString(SEXP xSEXP, SEXP intervalSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< CharacterVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type interval(intervalSEXP);
    __result = Rcpp::wrap(parseString(x, interval));
    return __result;
END_RCPP
}
